# What is machine learning?

Machine learning turning things (data - images, text, tables of numbers, video or audio numbers) into numbers and *finding parterns* (code & math) in those numbers.

A machine learning algorithm typically takes some inputs and some desired output, and then figures out rules, the patterns between inputs and output. Supervised learning - you have some kind of input with some kind of output (features also labels).
The machine learning algorithm job is to figure out the relationship between the inputs, or features, and the outputs, or labels.

Artificial intellegence -> { machine learning -> {deep learning}}. *Deep learning* is a subset of machine learning.

## Deep learning
What deep learning is good for?

* problems with long list of rules (self-driving car).
* continually changing envirement - it can adapt to new scenarios.
* discovering insights within large collections of data.

Data can be structured (tables of numbers - rows and columns - **best algorithm: gradient boosted machine**) and unstructured data (text, natural language, whole banch of text in wikipedia, images, video, audio - **algorithm: neural network**). If you have structured data, use XGBoost rather than deep learning. Deep learning is typically better for unstructured data.

## Machine learning - structured data
* Random forest
* Gradient boosted medels
* Naive Bayes
* Nearest neighbour
* Support vector machine

## Deep learning - unstructured data
* Neural networks
* fully connected neural network
* Convolutional neural network
* Recurrent neural netwrok
* Transformer

# Neural networks
* we have some inputs (unstructured data - images, text, video, audio) - **Inputs**.
* Before data gets used with a neural network, it neeeds to be turned into numbers - **Numerical encoding**.
* choose the appropiate neural network for your problem - **Learns represatation/features/weights** (Input layer- multiple hidden layer - output layer).
* representation outputs - numbers.
* output.

## Types of learning
* supervised learning - a lot of data and a lot of example of what that inputs should ideally look like. Maybe, indentifying between cat or dog (1000 of cat photos and 1000 of dog photos). So, we have data and labels.
* unsupervised learning - you just have the data itself, you dont have any labels. So, it learns solely from data itself, no labels.
* transfer learning - it takes the patterns one model has learned over dataset and tranforing it to another model





## 00. PyTorch fundementals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


### Random Tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

Start with random numbers -> look at data ->update random numbers -> look -> updata

In [ ]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
print(f"Dimension of tensor: {TENSOR.ndim}")
print(f"Shape of tensor: {TENSOR.shape}")
print(f"Datatype of tensor: {TENSOR.dtype}")

Dimension of tensor: 3
Shape of tensor: torch.Size([1, 3, 3])
Datatype of tensor: torch.int64


In [ ]:
# create some tensors with specific datatypes
float_32_tensor = torch.tensor([6.0, 3.0, 11.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

print(f"Dimension of tensor: {float_32_tensor.ndim}")
print(f"Shape of tensor: {float_32_tensor.shape}")
print(f"Datatype of tensor: {float_32_tensor.dtype}")
print(float_32_tensor)

Dimension of tensor: 1
Shape of tensor: torch.Size([3])
Datatype of tensor: torch.float32
tensor([ 6.,  3., 11.])


*Getting information from tensors*

`shape` - what shape is the tensor? (some operations require specific shape rules)

`dtype` - what datatype are the elements within the tensor stored in?

`device` - what device is the tensor stored on? (usually GPU or CPU)

### Random tensors

Why random tensors?

Random tensors are important beacuse the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.2267, 0.7696, 0.0181, 0.3605],
        [0.4405, 0.2977, 0.0181, 0.2286],
        [0.7694, 0.5288, 0.8511, 0.2546]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [ ]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8280, 0.2969, 0.3508, 0.5108],
        [0.5089, 0.9551, 0.1184, 0.5803],
        [0.4192, 0.9986, 0.5661, 0.1137]])

In [ ]:
# create arandom tensor with similar to an image tensor
# hieght, width, color channels
random_image_size_tensor = torch.rand(size=(3, 224, 224))

print(f"Random image size tensor: {random_image_size_tensor.shape}")
print(f"Random image dim tensor: {random_image_size_tensor.ndim}")
print(f"Random image dtype tensor: {random_image_size_tensor.dtype}")

Random image size tensor: torch.Size([3, 224, 224])
Random image dim tensor: 3
Random image dtype tensor: torch.float32


### Creatinf a range of tensors

In [ ]:
torch.arange(0, 10)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.__version__

'2.3.0+cu121'

### Tenosr datatype
Three big errors:
1. Tensors not right datatype.
2. Tensros not right shape.
3. Tensors not right device.

In [ ]:
float_32_tensor = torch.tensor([3.0, 5.0, 9.0],
                               dtype=None, # what datatype is the tensor, default is float32
                               device=None, # in what device is your tensor
                               requires_grad=False) # whether or not to trach gradients with this tensors operations

float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
tensor = torch.tensor([1,2,3])
tensor.dtype

torch.int64

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.68 ms, sys: 960 µs, total: 2.64 ms
Wall time: 7.11 ms


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.72 ms, sys: 74 µs, total: 1.79 ms
Wall time: 12 ms


tensor(14)

### Finding the positional min and max

In [ ]:
x = torch.arange(0, 100, 11)
x

tensor([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [ ]:
# find the position in tensor that has the minimum value with argmin() - returns the index of the minimum value
print(torch.argmin(x), x.argmin())

tensor(0) tensor(0)


In [ ]:
# find the position with the maximum value
print(torch.argmax(x), x.argmax())

tensor(9) tensor(9)


### Reshaping, stacking, squuezing and unsquuezing
* Reshaping - reshapes an input tenor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor.
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack).
* Squueze - removes all `1` dimensions from a tensor.
* Unsquueze - adds  a `1` dimension to a target tensor.
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way.

In [ ]:
import torch
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
# change the view
z = x.view(1, 9)  # z has the same memory as x
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
# stack tensors
x_stacked = torch.stack([x, x, x, x], dim=0) #
x_stacked

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

### GPU access with PyTorch

In [ ]:
import torch
torch.cuda.is_available()

False

In [ ]:
# setup a device aagnostic code
devi